# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os


# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
cities_csv_path = "/Users/bader/Desktop/BootCamp_HW_Assignments/HW6(API)/python_api_challenge/vacationpy/cities.csv"
city_data = pd.read_csv(cities_csv_path)
city_data

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,rikitea,-23.12,-134.97,23.67,82,99,6.10,PF,1603902909
1,1,mataura,-46.19,168.86,8.89,90,93,0.89,NZ,1603902994
2,2,busselton,-33.65,115.33,14.44,47,0,5.41,AU,1603902994
3,3,dikson,73.51,80.55,-15.47,93,28,9.82,RU,1603902994
4,4,albany,42.60,-73.97,8.33,90,100,0.53,US,1603902853
...,...,...,...,...,...,...,...,...,...,...
563,563,athens,37.98,23.72,17.22,93,75,3.10,GR,1603903043
564,564,nea alikarnassos,35.33,25.17,21.00,60,40,7.20,GR,1603903090
565,565,asfi,32.30,-9.24,21.18,57,0,9.71,MA,1603903090
566,566,kamaishi,39.27,141.88,13.51,79,70,5.47,JP,1603903090
567,567,soure,-0.72,-48.52,30.84,61,0,6.28,BR,1603903090

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
gmaps.configure(api_key=g_key)

# Storing latitude and longitude in locations
locations = city_data[["Lat", "Lng"]]

# Fill NaN values and convert to float
humidity = city_data["Humidity"].astype(float)

In [5]:
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)



fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure