# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os


# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
cities_csv_path = "/Users/bader/Desktop/BootCamp_HW_Assignments/HW6(API)/python_api_challenge/vacationpy/cities.csv"
city_data = pd.read_csv(cities_csv_path)
city_data

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,rikitea,-23.12,-134.97,74.79,75,75,11.77,PF,1604001390
1,1,mataura,-46.19,168.86,55.00,90,100,1.99,NZ,1604001295
2,2,busselton,-33.65,115.33,57.99,45,0,12.75,AU,1604001393
3,3,dikson,73.51,80.55,5.90,92,100,23.17,RU,1604001406
4,4,albany,42.60,-73.97,46.00,90,100,2.75,US,1604001391
...,...,...,...,...,...,...,...,...,...,...
563,563,athens,37.98,23.72,64.99,77,20,3.00,GR,1604001731
564,564,nea alikarnassos,35.33,25.17,66.20,77,20,7.34,GR,1604001858
565,565,asfi,32.30,-9.24,69.84,63,20,10.76,MA,1604001858
566,566,kamaishi,39.27,141.88,46.08,70,37,5.03,JP,1604001435
567,567,soure,-0.72,-48.52,83.80,72,94,13.15,BR,1604001858

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)

# Storing latitude and longitude in locations
locations = city_data[["Lat", "Lng"]]

# Fill NaN values and convert to float
humidity = city_data["Humidity"].astype(float)

In [4]:
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1
                                 )



fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
city_data["Cloudiness"].value_counts().head(10)

0      110
100    101
75      46
40      36
90      34
20      31
1       19
97       8
96       7
95       7
Name: Cloudiness, dtype: int64

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [17]:
 perfect_temp = city_data.loc[(city_data["Max Temp"]>70)&(city_data["Max Temp"]<80)&(city_data["Wind Speed"]<13)&(city_data["Cloudiness"]<10)]
#perfect_temp.dropna(inplace = True) = there are no NaN for my dataset
perfect_temp

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
23,23,pacific grove,36.62,-121.92,75.00,45,1,8.05,US,1604001797
28,28,viedma,-40.81,-63.00,73.00,20,0,1.99,AR,1604001797
33,33,xai-xai,-25.05,33.64,72.68,81,0,10.22,MZ,1604001798
40,40,kapaa,22.08,-159.32,77.00,64,1,3.36,US,1604001283
42,42,saint george,37.10,-113.58,72.00,17,1,0.89,US,1604001607
125,125,kalabo,-14.97,22.68,75.15,53,6,5.06,ZM,1604001806
127,127,sunrise manor,36.21,-115.07,75.99,14,1,5.82,US,1604001604
134,134,salalah,17.02,54.09,78.80,69,0,3.36,OM,1604001546
184,184,namibe,-15.20,12.15,70.66,72,3,10.71,AO,1604001497
214,214,wamba,8.93,8.60,76.57,58,6,2.53,NG,1604001817
248,248,telimele,10.92,-13.33,74.07,56,5,2.15,GN,1604001822
250,250,bilma,18.69,12.92,76.53,16,0,6.49,NE,1604001428
279,279,presidencia roque saenz pena,-26.79,-60.44,79.00,21,5,7.00,AR,1604001578
288,288,marsa matruh,31.35,27.25,71.60,56,0,5.82,EG,1604001826
304,304,guerrero negro,27.98,-114.06,79.70,17,3,2.66,MX,1604001828
315,315,buraydah,26.33,43.98,71.60,24,0,6.22,SA,1604001385
316,316,birpur,26.52,87.02,72.46,63,0,2.21,IN,1604001829
338,338,san francisco,37.77,-122.42,73.00,59,1,3.36,US,1604001699
340,340,ormara,25.21,64.64,76.17,56,0,6.51,PK,1604001832
354,354,walla walla,46.06,-118.34,73.00,32,1,5.82,US,1604001834
391,391,san quintin,30.48,-115.95,73.76,37,0,8.90,MX,1604001839
394,394,tura,25.52,90.22,71.37,86,0,4.32,IN,1604001839
421,421,bara,10.37,10.73,78.98,36,0,1.30,NG,1604001843
439,439,half moon bay,37.46,-122.43,72.00,55,5,3.36,US,1604001809
440,440,hillsborough,37.57,-122.38,72.00,59,1,3.36,US,1604001844
472,472,manado,1.49,124.85,77.81,82,5,4.36,ID,1604001426
475,475,sertanopolis,-23.06,-51.04,75.20,69,0,9.17,BR,1604001725
490,490,lompoc,34.64,-120.46,75.99,23,1,8.59,US,1604001451
500,500,siyabuswa,-25.11,29.04,75.09,20,0,9.15,ZA,1604001851
503,503,nabisar,25.07,69.64,79.43,32,0,5.91,PK,1604001852
513,513,boffa,10.17,-14.03,79.29,82,0,3.76,GN,1604001853
518,518,agadez,19.75,10.25,75.00,18,0,8.88,NE,1604001853
519,519,sur,22.57,59.53,72.16,55,0,1.12,OM,1604001454
531,531,bewar,27.22,79.30,70.52,27,0,2.84,IN,1604001855

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [54]:
hotel_df = pd.DataFrame(perfect_temp)

hotel_df["Hotel Name"] = ""

hotel_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
23,23,pacific grove,36.62,-121.92,75.00,45,1,8.05,US,1604001797,
28,28,viedma,-40.81,-63.00,73.00,20,0,1.99,AR,1604001797,
33,33,xai-xai,-25.05,33.64,72.68,81,0,10.22,MZ,1604001798,
40,40,kapaa,22.08,-159.32,77.00,64,1,3.36,US,1604001283,
42,42,saint george,37.10,-113.58,72.00,17,1,0.89,US,1604001607,
125,125,kalabo,-14.97,22.68,75.15,53,6,5.06,ZM,1604001806,
127,127,sunrise manor,36.21,-115.07,75.99,14,1,5.82,US,1604001604,
134,134,salalah,17.02,54.09,78.80,69,0,3.36,OM,1604001546,
184,184,namibe,-15.20,12.15,70.66,72,3,10.71,AO,1604001497,
214,214,wamba,8.93,8.60,76.57,58,6,2.53,NG,1604001817,
248,248,telimele,10.92,-13.33,74.07,56,5,2.15,GN,1604001822,
250,250,bilma,18.69,12.92,76.53,16,0,6.49,NE,1604001428,
279,279,presidencia roque saenz pena,-26.79,-60.44,79.00,21,5,7.00,AR,1604001578,
288,288,marsa matruh,31.35,27.25,71.60,56,0,5.82,EG,1604001826,
304,304,guerrero negro,27.98,-114.06,79.70,17,3,2.66,MX,1604001828,
315,315,buraydah,26.33,43.98,71.60,24,0,6.22,SA,1604001385,
316,316,birpur,26.52,87.02,72.46,63,0,2.21,IN,1604001829,
338,338,san francisco,37.77,-122.42,73.00,59,1,3.36,US,1604001699,
340,340,ormara,25.21,64.64,76.17,56,0,6.51,PK,1604001832,
354,354,walla walla,46.06,-118.34,73.00,32,1,5.82,US,1604001834,
391,391,san quintin,30.48,-115.95,73.76,37,0,8.90,MX,1604001839,
394,394,tura,25.52,90.22,71.37,86,0,4.32,IN,1604001839,
421,421,bara,10.37,10.73,78.98,36,0,1.30,NG,1604001843,
439,439,half moon bay,37.46,-122.43,72.00,55,5,3.36,US,1604001809,
440,440,hillsborough,37.57,-122.38,72.00,59,1,3.36,US,1604001844,
472,472,manado,1.49,124.85,77.81,82,5,4.36,ID,1604001426,
475,475,sertanopolis,-23.06,-51.04,75.20,69,0,9.17,BR,1604001725,
490,490,lompoc,34.64,-120.46,75.99,23,1,8.59,US,1604001451,
500,500,siyabuswa,-25.11,29.04,75.09,20,0,9.15,ZA,1604001851,
503,503,nabisar,25.07,69.64,79.43,32,0,5.91,PK,1604001852,
513,513,boffa,10.17,-14.03,79.29,82,0,3.76,GN,1604001853,
518,518,agadez,19.75,10.25,75.00,18,0,8.88,NE,1604001853,
519,519,sur,22.57,59.53,72.16,55,0,1.12,OM,1604001454,
531,531,bewar,27.22,79.30,70.52,27,0,2.84,IN,1604001855,

In [56]:
hotel_name = []
coordinates = f"{hotel_df['Lat'][0]}, {hotel_df['Lng'][0]}"

for index, row in hotel_df.iterrows():
    params = {
    "location": coordinates,
    "keyword": "hotel",
    "radius": 5000,
    "type": "hotel",
    "key": g_key
    }

    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    response = requests.get(base_url, params=params)
    response_json = response.json()
    try:
        hotel_name.append(response_json['results'][0]['name'])
    except:
        hotel_name.append("")

hotel_df["Hotel Name"] = hotel_name
hotel_df.head()

KeyError: 0

In [36]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [53]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content=[f"Hotel Name: {hotel}" for hotel in hotel_name])
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))